---
 - hosts: webserver
   tasks:
     - name: copy code from git hub
       git:
         repo: https://github.com/ramvish52/newweb.git
         dest: /var/www/html
         force: no       
       notify:
         - restart_apache

   handlers:
     - name: restart_apache

       service:
         name: httpd
         state: restarted           

