---
  - name: install the {{ package }} package
    yum:
      name: "{{ package }}"
      state: latest
  - name: start the {{ service }}
    service:
      name: "{{ service }}"
      state: "{{ svc_state }}"      
