---
  - name: Install and start the database and web servers
    yum:
      name:
        - "{{ ansible_local.custom.packages.db_package }}"
        - "{{ ansible_local.custom.packages.web_package }}"
      state: latest

  - name: start the database service
    service:
      name: "{{ ansible_local.custom.services.db_service }}"
      state: started
      enabled: true

  - name: start the web service
    service:
      name: "{{ ansible_local.custom.services.db_service }}"
      state: started
      enabled: true
